// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTSzaUkAmqgHXjdX6zBvti9TwBHMCMhyE',
    appId: '1:725581954382:web:08c766ec3b1165f462f21f',
    messagingSenderId: '725581954382',
    projectId: 'un-lugar-chido',
    authDomain: 'un-lugar-chido.firebaseapp.com',
    storageBucket: 'un-lugar-chido.appspot.com',
    measurementId: 'G-NN147T1G6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpphlODU7twg7s3Ay1PS4ptbyeAD0cxs8',
    appId: '1:725581954382:android:dcb66b5bde80490062f21f',
    messagingSenderId: '725581954382',
    projectId: 'un-lugar-chido',
    storageBucket: 'un-lugar-chido.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Ny_wmhWaZk87JkwQicnfCCjFa0EhMUA',
    appId: '1:725581954382:ios:4cefcaf8c7eab3c762f21f',
    messagingSenderId: '725581954382',
    projectId: 'un-lugar-chido',
    storageBucket: 'un-lugar-chido.appspot.com',
    iosBundleId: 'com.example.unLugarChidoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Ny_wmhWaZk87JkwQicnfCCjFa0EhMUA',
    appId: '1:725581954382:ios:4cefcaf8c7eab3c762f21f',
    messagingSenderId: '725581954382',
    projectId: 'un-lugar-chido',
    storageBucket: 'un-lugar-chido.appspot.com',
    iosBundleId: 'com.example.unLugarChidoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTSzaUkAmqgHXjdX6zBvti9TwBHMCMhyE',
    appId: '1:725581954382:web:6a17ef9966a6ccda62f21f',
    messagingSenderId: '725581954382',
    projectId: 'un-lugar-chido',
    authDomain: 'un-lugar-chido.firebaseapp.com',
    storageBucket: 'un-lugar-chido.appspot.com',
    measurementId: 'G-JQGLRW6LYD',
  );
}
